-- Create the table for chemistry_concept
CREATE TABLE chemistry_concept (
    id SERIAL PRIMARY KEY,
    grade VARCHAR(255),
    type VARCHAR(255),
    concept TEXT
);

-- Insert data into the chemistry_concept table
INSERT INTO chemistry_concept (grade, type, concept) VALUES
('6', 'Theory', 'States of Matter: Solid, Liquid, Gas.'),
('6', 'Theory', 'Chemical Reactions: Combustion, Oxidation, Reduction.'),
('6', 'Theory', '(low pH) Acid - Neutral - Alkali (high pH).'),
('6', 'Theory', 'Chemical change results in a new substance and it cannot be reversed by physical means.'),
('6', 'Theory', 'A chemical substance is a unique form of matter with constant chemical composition and characteristic properties.'),
('6', 'Formula', 'Density = Mass / Volume'),
('6', 'Formula', 'pH = -log[H+]'),
('6', 'Formula', 'Boyle''s Law: P1V1 = P2V2'),
('6', 'Formula', 'Charles''s Law: V1 / T1 = V2 / T2'),
('6', 'Formula', 'Speed of Reaction = Amount of Reactant / Time'),
('7', 'Theory', 'Atomic Structure: Protons, Neutrons, Electrons'),
('7', 'Theory', 'Chemical Bonding: Ionic, Covalent, Metallic'),
('7', 'Theory', 'Chemical reactions involve breaking chemical bonds between reactant molecules (particles) and forming new bonds between atoms in product particles (molecules).'),
('7', 'Theory', 'Types of Chemical Reactions: Synthesis, Decomposition, Single Replacement, Double Replacement'),
('7', 'Theory', 'Chemical equations and Stoichiometry: The coefficients in the balanced chemical equation tell how many moles of reactants are needed and how many moles of product can be produced.'),
('7', 'Formula', 'Molar Mass = Mass of Substance / Amount of Substance'),
('7', 'Formula', 'Avogadro''s Law: V1 / n1 = V2 / n2'),
('7', 'Formula', 'Ideal Gas Law: PV = nRT'),
('7', 'Formula', 'NaOH + HCl -> NaCl + H2O.'),
('7', 'Formula', 'Mg(s) + 2HCl(aq) -> MgCl2(aq) + H2(g)'),
('8', 'Theory', 'Chemical Nomenclature: Prefixes are used to dictate the number of a given element present in the compound.'),
('8', 'Theory', 'Chemical Kinetics: Rate Laws, Reaction Mechanisms.'),
('8', 'Theory', 'Acid-Base Reactions: pH Scale, Indicators. Neutral litmus paper is purple; it turns red in the presence of an acid and blue in the presence of a base.'),
('8', 'Theory', 'Acidic: pH < 7, Basic (Alkalic): pH > 7, Neutral: pH = 7.'),
('8', 'Theory', 'Electrochemistry: Electrolysis, Galvanic Cells.'),
('8', 'Formula', 'Dilution Formula: M1V1 = M2V2'),
('8', 'Formula', 'Rate of Reaction = Change in Concentration / Time'),
('8', 'Formula', 'Henderson - Hasselbalch Equation: pH = pKa + log([A-]/[HA])'),
('8', 'Formula', 'Nernst Equation: Ecell = E°cell - (0.0592/n) * log(Q)'),
('8', 'Formula', 'Faraday''s Law of Electrolysis: moles of substance = (charge passed) / (Faraday''s constant)'),
('9', 'Theory', 'Chemical Thermodynamics: Enthalpy, Entropy, Gibbs Free Energy.'),
('9', 'Theory', 'Chemical Equilibrium - Le Chatelier''s Principle: a pressure increase shifts an equilibrium to the side of the reaction with the fewer number of moles of gas.'),
('9', 'Theory', 'Organic Chemistry: Hydrocarbons, Functional Groups.'),
('9', 'Theory', 'Polymer Chemistry: Polymerization, Types of Polymers.'),
('9', 'Theory', 'Nuclear Chemistry: Radioactivity, Half-Life, Fission, Fusion.'),
('9', 'Formula', 'Gibbs Free Energy Change = ∆H - T∆S'),
('9', 'Formula', 'Equilibrium Constant (Kc) = [Products] / [Reactants]'),
('9', 'Formula', 'Activation Energy and Arrhenius Equation: k = Ae^(-Ea/RT)'),
('9', 'Formula', 'NMR Spectroscopy: δ = ppm scale'),
('9', 'Formula', 'Pressure in Liquid: P = Patm + hpg'),
('10', 'Theory', 'Chemical Bonds: Hybridization leads to different Orbital Geometries, such as linear, trigonal planar, tetrahedral, trigonal bipyramidal, and octahedral.'),
('10', 'Theory', 'Intermolecular Forces: Hydrogen Bonding, London Dispersion Forces.'),
('10', 'Theory', 'Chemical Analysis: Spectroscopy, Chromatography.'),
('10', 'Theory', 'Redox Reactions: Oxidation Numbers, Balancing Redox Equations.'),
('10', 'Theory', 'Coordination Compounds: Ligands, Coordination Number, Isomerism.'),
('10', 'Formula', 'Beer-Lambert Law: A = εlc'),
('10', 'Formula', 'Faraday''s Law: q = nF'),
('10', 'Formula', 'Rate Law Expression: rate = k[A]^m[B]^n'),
('10', 'Formula', 'Gibbs-Helmholtz Equation: ∆G = ∆H - T∆S'),
('10', 'Formula', 'Mg(HCO3)2 +2HCL -> MGCl2 + H2O + CO2(g)'),
('11', 'Theory', 'Kinetics: Reaction Rates, Rate Laws, Activation Energy.'),
('11', 'Theory', 'Acids and Bases: Brønsted-Lowry Theory, pH Calculations.'),
('11', 'Theory', 'Solubility Equilibria: Ksp, Common Ion Effect.'),
('11', 'Theory', 'Classification of Elements and Periodicity: grouping elements in accordance to their properties led to the development of Periodic Table.'),
('11', 'Theory', 'Intermolecular force (IMF)is the force that mediates interaction between molecules, including electromagnetic forces of attraction or repulsion.'),
('11', 'Formula', 'Rate Constant (k) = A * e^(-Ea/RT)'),
('11', 'Formula', 'Solubility Product (Ksp) = [Product Ions]^m * [Reactant Ions]^n'),
('11', 'Formula', 'For a general solubility reaction, Ax By (s) -> xA(aq) + yB(aq)'),
('11', 'Formula', 'pH of Salt Solutions: pH = 7 + log(Ka/Kb)'),
('11', 'Formula', 'Intermolecular Force: F = k / r6'),
('12', 'Theory', 'Functional groups organic chemistry: common examples of functional groups are alcohols, alkenes, alkynes, amines, carboxylic acids, aldehydes, ketones, esters, and ethers.'),
('12', 'Theory', 'Electrochemistry: Electrolytic Cells, Nernst Equation, Electrode Potentials.'),
('12', 'Theory', 'Orbital hybridisation (or hybridization) is the concept of mixing atomic orbitals to form new hybrid orbitals (with different energies, shapes, etc.'),
('12', 'Theory', 'Nuclear Chemistry: Radioactive Decay, Nuclear Reactions, Applications. Nuclear decay reactions convert one unstable isotope (or radioisotope) into another, more stable, isotope.'),
('12', 'Theory', 'Combustion reaction: Chemical reaction in which a reaction between any combustible substance and an oxidiser takes place in order to form an oxidised product.'),
('12', 'Formula', 'pH of Buffers: pH = pKa + log([A-]/[HA])'),
('12', 'Formula', 'Combustion general formula: Fuel + O2 → CO2 + H2O'),
('12', 'Formula', 'Solid density of a unit cell: d = (Z x M) / (a^3 * Na)'),
('12', 'Formula', 'Packing efficiency = Volume occupied by 6 spheres ×100 / Total volume of unit cells. (i.e., Magnesium, Titanium, Beryllium).'),
('12', 'Formula', 'Dissociation constant of weak electrolyte: K = Cα^2 / (1-α) with α = ʌcm / ʌom');
