-- Create the table for physics_concept
CREATE TABLE physics_concept (
    id SERIAL PRIMARY KEY,
    grade VARCHAR(255),
    type VARCHAR(255),
    concept TEXT
);

-- Insert data into the physics_concept table
INSERT INTO physics_concept (grade, type, concept) VALUES
('6', 'Theory', 'Newton''s first law of motion: An object at rest remains at rest, or if in motion, remains in motion at a constant velocity unless acted on by a net external force.'),
('6', 'Theory', 'Types of Energy: Kinetic, Potential, Mechanical, Heat, Light, Sound.'),
('6', 'Theory', 'Simple Machines: Lever, Pulley, Wheel and Axle, Inclined Plane, Wedge, Screw.'),
('6', 'Theory', 'Types of Forces: Gravity, Friction, Magnetic, Electrical.'),
('6', 'Theory', 'Measurement and Units: Length, Mass, Time, Volume, Density, Speed.'),
('6', 'Formula', 'Force = Mass × Acceleration (F = ma)'),
('6', 'Formula', 'Work = Force × Distance (W = Fd)'),
('6', 'Formula', 'Kinetic Energy = 0.5 × Mass × Velocity^2 (KE = 0.5mv^2)'),
('6', 'Formula', 'Gravitational Potential Energy = Mass × Gravity × Height (PE = mgh)'),
('6', 'Formula', 'Density = Mass / Volume (ρ = m/V)'),
('7', 'Theory', 'Light: Reflection, Refraction, Dispersion.'),
('7', 'Theory', 'Newton''s second law states that the acceleration of an object is directly related to the net force and inversely related to its mass.'),
('7', 'Theory', 'Electricity: Circuits, Conductors, Insulators, Ohm''s Law.'),
('7', 'Theory', 'Magnetism: Magnetic Fields, Magnetic Force, Electromagnetism.'),
('7', 'Theory', 'Heat Transfer: Conduction, Convection, Radiation.'),
('7', 'Formula', 'Speed = Distance / Time (v = d/t)'),
('7', 'Formula', 'Acceleration = Change in Velocity / Time (a = Δv/t)'),
('7', 'Formula', 'Force = Spring Constant × Displacement (F = kx)'),
('7', 'Formula', 'Ohm''s Law: Voltage = Current × Resistance (V = IR)'),
('7', 'Formula', 'Momentum: Momentum = mass x velocity (p = mv)'),
('8', 'Theory', 'Waves: Types, Properties, Wave Behavior.'),
('8', 'Theory', 'Optics: Lenses, Mirrors, Snell''s Law.'),
('8', 'Theory', 'Electricity and Magnetism: Electromagnetic Induction, Faraday''s Law. Whenever a conductor is placed in a varying magnetic field, an electromotive force is induced.'),
('8', 'Theory', 'Energy: Conservation of Energy, Energy Transformation.'),
('8', 'Theory', 'Fluid Dynamics: Pressure, Buoyancy, Bernoulli''s Principle. The pressure in a fluid decreases as the fluid''s velocity increases.'),
('8', 'Formula', 'Wave Speed = Frequency × Wavelength (v = fλ)'),
('8', 'Formula', 'Index of Refraction = Speed of Light in Vacuum / Speed of Light in Material (n = c/v)'),
('8', 'Formula', 'Faraday''s Law of Electromagnetic Induction: EMF = -N ΔΦ/Δt'),
('8', 'Formula', 'Conservation of Energy: Total Energy = Kinetic Energy + Potential Energy (E = KE + PE)'),
('8', 'Formula', 'Pressure = Force / Area (P = F/A)'),
('9', 'Theory', 'Gravity: Gravitational Force, Orbits, Kepler''s Laws.'),
('9', 'Theory', 'Atomic Structure: Subatomic Particles, Electron Configuration.'),
('9', 'Theory', 'Thermodynamics: Laws, Heat Engines, Entropy. Describe how the energy in a system changes and whether the system can perform useful work on its surroundings.'),
('9', 'Theory', 'Electric Circuits: Kirchhoff''s Laws, Series and Parallel Circuits.'),
('9', 'Theory', 'Wave Behaviour: Interference, Diffraction, Polarisation.'),
('9', 'Formula', 'Gravitational Force = G × (m1 × m2) / r^2'),
('9', 'Formula', 'Bohr''s Model: Energy Levels = -13.6eV / n^2'),
('9', 'Formula', 'First Law of Thermodynamics: ΔU = Q - W'),
('9', 'Formula', 'Heat of Fusion: q = m * ΔHF'),
('9', 'Formula', 'Latent Heat: L = Q / M'),
('10', 'Theory', 'Electromagnetism: Maxwell''s Equations, Electromagnetic Waves. c = 1√μ0ϵ0.'),
('10', 'Theory', 'Quantum Mechanics: Wave-Particle Duality, Heisenberg Uncertainty Principle.'),
('10', 'Theory', 'Special Relativity: Time Dilation, Length Contraction, Mass-Energy Equivalence.'),
('10', 'Theory', 'Nuclear Physics: Nuclear Decay, Radioactive Half-Life, Nuclear Reactions.'),
('10', 'Theory', 'Astrophysics: Stellar Evolution, Cosmology, Black Holes. Stellar-mass black holes likely originated as mismatched stars where the more massive one evolved rapidly into a black hole.'),
('10', 'Formula', 'Maxwell''s Equations: ∇⋅E = ρ/ε0, ∇⋅B = 0, ∇×E = -∂B/∂t, ∇×B = μ0J + μ0ε0 ∂E/∂t'),
('10', 'Formula', 'de Broglie Wavelength: λ = h / p'),
('10', 'Formula', 'Time Dilation: Δt'' = Δt / √(1 - v^2/c^2)'),
('10', 'Formula', 'Half-Life: t1/2 = (ln 2) / λ'),
('10', 'Formula', 'Schwarzschild Radius: Rs = 2GM / c^2'),
('11', 'Theory', 'Particle Physics: Standard Model, Fundamental Forces.'),
('11', 'Theory', 'String Theory: Extra Dimensions, Vibrating Strings.'),
('11', 'Theory', 'Cosmology: Big Bang Theory, Dark Matter, Dark Energy. Dark matter governs the cosmos, forming galaxies and galaxy clusters; dark energy control the future, pushing galaxies farther apart'),
('11', 'Theory', 'Quantum Field Theory: Field Particles, Quantum Fluctuations. Quantum fluctuation is the temporary random change in the amount of energy in a point in space,'),
('11', 'Theory', 'General Relativity: Curved Spacetime, Gravitational Waves.'),
('11', 'Formula', 'Standard Model: Describes Electromagnetic, Weak, and Strong Nuclear Interactions.'),
('11', 'Formula', 'String Tension: T = (F/A) × L'),
('11', 'Formula', 'Critical Density: ρc = 3H^2 / 8πG'),
('11', 'Formula', 'Vacuum Energy: E = ħ × ω / 2'),
('11', 'Formula', 'Einstein Field Equations: Gμν = 8πGTμν'),
('12', 'Theory', 'Black Hole Thermodynamics: Hawking Radiation, Entropy of Black Holes.'),
('12', 'Theory', 'Grand Unified Theory (GUT): Unification of Fundamental Forces.'),
('12', 'Theory', 'Multiverse Theory: Parallel Universes, Cosmic Inflation.'),
('12', 'Theory', 'Quantum Gravity: Unified Theory of Gravity and Quantum Mechanics.'),
('12', 'Theory', 'Extra Dimensions: Kaluza-Klein Theory, String Theory.'),
('12', 'Formula', 'Hawking Radiation: L = (ħc^3) / (16πGM^2)'),
('12', 'Formula', 'GUT Energy Scale: ΛGUT ≈ 10^16 GeV'),
('12', 'Formula', 'Multiverse Probability: P = ∫ |Ψ|^2 dV'),
('12', 'Formula', 'Quantum Gravity Energy: E = ħc^5 / (32πGħ)'),
('12', 'Formula', 'Kaluza-Klein Compactification: R = r0 + α'' ln(M^2 r0)');
